### ISSUE TITLE
Getting this error after hitting "0.0.0.0:3000"

### ISSUE THREAD

**Issue by rahul8sharma** [brentkearney/workshops#26]
Error: File to import not found or unreadable: vali-admin/src/sass/1-tools/_fonts.scss.
        on line 10:1 of vendor/assets/stylesheets/val-admin.scss
        from line 2:1 of app/assets/stylesheets/application.scss
>> @import 'vali-admin/src/sass/1-tools/_fonts.scss';

**Comment by brentkearney** [comment]
Thanks for reporting this. It seems that I didn't add [vali-admin](https://github.com/brentkearney/vali-admin) to git, entirely.

**Comment by brentkearney** [comment]
The `vali-admin` files are part of its NPM package. I think you just need to run yarn to install the NPM packages. Try updating the [package.json](https://github.com/brentkearney/workshops/blob/master/package.json) file, and run:
```
yarn install
yarn add webpack-cli -D
```

I have updated the example entrypoint.sh script (for Docker), and the `package.json` file in the master branch. 🍻
