### ISSUE TITLE
Migration uses "USING CAST()" which is not compatible with sqlite3

### ISSUE THREAD

**Issue by fwolfst** [brentkearney/workshops#5]
Migration `db/migrate/20160225235932_change_staff_item_to_boolean.rb` calls

    change_column :schedules, :staff_item, 'boolean USING CAST(staff_item AS boolean)', null: false, default: false

Note that this only occurs when calling `rails db:migrate` . The (prefered) `rails db:schema:load` will have the database set up just fine.

**Comment by fwolfst** [comment]
And I think its totally fine. Closing the issue.

**Comment by brentkearney** [comment]
Thanks for reporting it -- if I do create another installation guide for sqlite3, I will remove `db:migrate` in favour of `db:schema:load`.
